# Generated by Django 5.2.7 on 2025-11-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='mascotas.especie'),
        ),
        migrations.AddField(
            model_name='raza',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='mascotas.especie'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='mascotas.raza'),
        ),
        migrations.AlterUniqueTogether(
            name='raza',
            unique_together={('nombre', 'especie')},
        ),
    ]
