# Generated by Django 5.2.7 on 2025-11-30 06:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('HEMOGRAMA', 'Hemograma completo'), ('QUIMICA_SANGUINEA', 'Química sanguínea'), ('URINALISIS', 'Urianálisis'), ('COPROLOGICO', 'Coprológico'), ('RAYOS_X', 'Rayos X'), ('ECOGRAFIA', 'Ecografía'), ('CITOLOGIA', 'Citología'), ('BIOPSIA', 'Biopsia'), ('ELECTROCARDIOGRAMA', 'Electrocardiograma'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de examen')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción adicional')),
                ('fecha_orden', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de orden')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['tipo_examen'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la historia')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado_vacunacion_actual', models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], default='', max_length=20, verbose_name='Estado de vacunación actual')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], max_length=20, verbose_name='Estado de vacunación')),
                ('vacunas_descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Vacunas pendientes/aplicadas')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Historial de Vacuna',
                'verbose_name_plural': 'Historial de Vacunas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('indicaciones', models.TextField(blank=True, default='', verbose_name='Indicaciones de uso')),
                ('fecha_prescripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de prescripción')),
            ],
            options={
                'verbose_name': 'Prescripción',
                'verbose_name_plural': 'Prescripciones',
                'ordering': ['fecha_prescripcion'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de consulta')),
                ('descripcion_consulta', models.TextField(verbose_name='Descripción de la consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('notas_adicionales', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('consentimiento_token', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Token de Consentimiento')),
                ('consentimiento_otorgado', models.BooleanField(default=False, verbose_name='Consentimiento Otorgado')),
                ('consentimiento_fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Consentimiento')),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulta_generada', to='citas.cita', verbose_name='Cita de origen')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
