# Generated by Django 5.2.7 on 2025-11-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('consultas', '0001_initial'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='mascotas.mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='citas.servicio', verbose_name='Servicio realizado'),
        ),
    ]
