# Generated by Django 5.2.7 on 2025-11-30 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to=models.Q(('usuario_roles__rol__nombre', 'veterinario'), ('usuario_roles__rol__nombre', 'practicante'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_veterinario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.servicio'),
        ),
    ]
